[package]
name = "apk-audit"
version = "0.1.0"
authors = ["Iban Eguia <razican@protonmail.ch>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/Razican/apk-audit-core"
documentation = "http://razican.github.io/apk-audit-core"
description = """
Android apk auditor. Core software with CLI.
"""
keywords = ["Android", "security", "audit"]

[dependencies]
clap = "^2.5"
colored = "^1.2"
zip = "^0.1"
xml-rs = "^0.3"
serde = "^0.7"
serde_json = "^0.7"
chrono = "^0.2"
toml = "^0.1"
regex = "^0.1"
rust-crypto = "0.2.36"
