# Vulnerable or potentially vulnerable permissions
[[permissions]]
name = "android.permission.INTERNET" # Internet access permission
criticity = "warning"
label = "Internet permission"
description = "The application has full access to network sockets. Check if the permission is actually needed."

[[permissions]]
name = "android.permission.READ_EXTERNAL_STORAGE" # External storage access
criticity = "warning"
label = "External storage write permission"
description = "The application has external storage read access. Check if the permission is actually needed."

[[permissions]]
name = "android.permission.WRITE_EXTERNAL_STORAGE" # External storage access
criticity = "warning"
label = "External storage write permission"
description = "The application has external storage write access. Check if the permission is actually needed."
